#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions.Env is 8c16g & noContainer logs &  3o1p2c
  clients:
    type: local
    number: 5
  rounds:
  - label: open
    txDuration:
    - 30
    rateControl:
    - type: linear-rate
      opts:
        startingTps: 200
        finishingTps: 1000
    arguments:
      money: 1000
    callback: benchmark/simple/open.js
  - label: query
    txDuration:
    - 30
    rateControl:
    - type: linear-rate
      opts:
        startingTps: 500
        finishingTps: 2000
    callback: benchmark/simple/query.js

observer:
  interval: 1
  type: local
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
